services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-ats-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - PORT=3000
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
