import { MigrationInterface, QueryRunner } from "typeorm";

export class AuditFixes1777666822285 implements MigrationInterface {
    name = 'AuditFixes1777666822285'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "candidate" DROP CONSTRAINT "FK_67170af9a05e67ebf48434db686"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP CONSTRAINT "FK_company_subscription_company"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP CONSTRAINT "FK_company_subscription_package"`);
        await queryRunner.query(`ALTER TABLE "screening_answer" DROP CONSTRAINT "FK_screening_answer_application"`);
        await queryRunner.query(`ALTER TABLE "screening_answer" DROP CONSTRAINT "FK_screening_answer_question"`);
        await queryRunner.query(`ALTER TABLE "screening_question" DROP CONSTRAINT "FK_screening_question_job"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "FK_contact_unlock_log_candidate"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "FK_contact_unlock_log_company"`);
        await queryRunner.query(`ALTER TABLE "payment_order" DROP CONSTRAINT "FK_payment_order_company"`);
        await queryRunner.query(`ALTER TABLE "payment_order" DROP CONSTRAINT "FK_payment_order_package"`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" DROP CONSTRAINT "FK_job_profile_view_candidate"`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" DROP CONSTRAINT "FK_job_profile_view_job"`);
        await queryRunner.query(`ALTER TABLE "credit_wallet" DROP CONSTRAINT "FK_credit_wallet_company"`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" DROP CONSTRAINT "FK_credit_transaction_wallet"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_credit_purchase_log_company"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_credit_purchase_log_job"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_credit_purchase_log_product"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_saved_job_candidate"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_saved_job_job"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67170af9a05e67ebf48434db68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_company_subscription_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_screening_answer_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_screening_question_job_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contact_unlock_log_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_order_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_order_gateway_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_profile_view_job_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_credit_transaction_wallet_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_credit_purchase_log_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_job_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_job_job_id"`);
        await queryRunner.query(`ALTER TABLE "screening_answer" DROP CONSTRAINT "UQ_screening_answer"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "UQ_contact_unlock_log"`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" DROP CONSTRAINT "UQ_job_profile_view"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "UQ_saved_job_candidate_job"`);
        await queryRunner.query(`ALTER TABLE "application_status_history" DROP COLUMN "credit_charged"`);
        await queryRunner.query(`ALTER TABLE "job_application" DROP COLUMN "screening_passed"`);
        await queryRunner.query(`ALTER TABLE "job_application" DROP COLUMN "ai_scored"`);
        await queryRunner.query(`ALTER TABLE "candidate" DROP COLUMN "level_id"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP COLUMN "headhunting_views_used"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP COLUMN "headhunting_views_reset_at"`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "bumped_at" TYPE TIMESTAMP WITH TIME ZONE USING "bumped_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "start_date" TYPE TIMESTAMP WITH TIME ZONE USING "start_date"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "end_date" TYPE TIMESTAMP WITH TIME ZONE USING "end_date"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "last_job_published_at" TYPE TIMESTAMP WITH TIME ZONE USING "last_job_published_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "proceeds_reset_at" TYPE TIMESTAMP WITH TIME ZONE USING "proceeds_reset_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "payment_method" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "paid_at" TYPE TIMESTAMP WITH TIME ZONE USING "paid_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "activated_at" TYPE TIMESTAMP WITH TIME ZONE USING "activated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "expires_at" TYPE TIMESTAMP WITH TIME ZONE USING "expires_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`CREATE INDEX "IDX_f8b117158ab95f921469ff24a3" ON "company_subscription" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fcad94dc3f7b8b86c2f454782" ON "screening_answer" ("application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1beaa4671be609e6a63b2b17ae" ON "screening_question" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_21824dd676afb8c2810ad30290" ON "contact_unlock_log" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd9e3b69626be360af7cf0d923" ON "contact_unlock_log" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17c31b236f5a8fcf717a4b6e5a" ON "payment_order" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5978c41e6e06f58a7db5259802" ON "job_profile_view" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f8a7f45f7acb51e680aa85cdd" ON "job_profile_view" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec74546492517ad86802c5c913" ON "credit_wallet" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f45e8a6455829dad6638dd0b1" ON "credit_transaction" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b75639be4adf19e9920f7c374" ON "credit_transaction" ("wallet_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_35b7a3621aa5ecdb3105c74e9f" ON "credit_purchase_log" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e08a5064905cd0c9513e39ce8b" ON "credit_purchase_log" ("company_id", "product_id", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f64c424d932c9718ec6da80e5" ON "saved_job" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7e38cdc6dc7765b30447cd06d" ON "saved_job" ("job_id") `);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "UQ_a6d0f15eff6e28524b4fa898602" UNIQUE ("company_id", "candidate_id")`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "UQ_0f5e404ec6b146ea06d1c429f6c" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD CONSTRAINT "FK_f8b117158ab95f921469ff24a3e" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD CONSTRAINT "FK_1656846e99e03d03402bf71a343" FOREIGN KEY ("package_id") REFERENCES "subscription_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_answer" ADD CONSTRAINT "FK_0fcad94dc3f7b8b86c2f4547820" FOREIGN KEY ("application_id") REFERENCES "job_application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_answer" ADD CONSTRAINT "FK_12362f6705c69bb8d04784b2c59" FOREIGN KEY ("question_id") REFERENCES "screening_question"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_question" ADD CONSTRAINT "FK_1beaa4671be609e6a63b2b17ae2" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "FK_21824dd676afb8c2810ad302903" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "FK_dd9e3b69626be360af7cf0d9237" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_order" ADD CONSTRAINT "FK_17c31b236f5a8fcf717a4b6e5a7" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_order" ADD CONSTRAINT "FK_2ece3b557a6023cb0efb17ae993" FOREIGN KEY ("package_id") REFERENCES "subscription_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" ADD CONSTRAINT "FK_5978c41e6e06f58a7db5259802f" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" ADD CONSTRAINT "FK_4f8a7f45f7acb51e680aa85cddc" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_wallet" ADD CONSTRAINT "FK_ec74546492517ad86802c5c9134" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" ADD CONSTRAINT "FK_6f45e8a6455829dad6638dd0b10" FOREIGN KEY ("wallet_id") REFERENCES "credit_wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_35b7a3621aa5ecdb3105c74e9f4" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_4f863c1623d4b461e4b24099c13" FOREIGN KEY ("product_id") REFERENCES "credit_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_0a78480d9c18f1872e2736f8216" FOREIGN KEY ("target_job_id") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_0f64c424d932c9718ec6da80e5d" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_d7e38cdc6dc7765b30447cd06d4" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_d7e38cdc6dc7765b30447cd06d4"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_0f64c424d932c9718ec6da80e5d"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_0a78480d9c18f1872e2736f8216"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_4f863c1623d4b461e4b24099c13"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" DROP CONSTRAINT "FK_35b7a3621aa5ecdb3105c74e9f4"`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" DROP CONSTRAINT "FK_6f45e8a6455829dad6638dd0b10"`);
        await queryRunner.query(`ALTER TABLE "credit_wallet" DROP CONSTRAINT "FK_ec74546492517ad86802c5c9134"`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" DROP CONSTRAINT "FK_4f8a7f45f7acb51e680aa85cddc"`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" DROP CONSTRAINT "FK_5978c41e6e06f58a7db5259802f"`);
        await queryRunner.query(`ALTER TABLE "payment_order" DROP CONSTRAINT "FK_2ece3b557a6023cb0efb17ae993"`);
        await queryRunner.query(`ALTER TABLE "payment_order" DROP CONSTRAINT "FK_17c31b236f5a8fcf717a4b6e5a7"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "FK_dd9e3b69626be360af7cf0d9237"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "FK_21824dd676afb8c2810ad302903"`);
        await queryRunner.query(`ALTER TABLE "screening_question" DROP CONSTRAINT "FK_1beaa4671be609e6a63b2b17ae2"`);
        await queryRunner.query(`ALTER TABLE "screening_answer" DROP CONSTRAINT "FK_12362f6705c69bb8d04784b2c59"`);
        await queryRunner.query(`ALTER TABLE "screening_answer" DROP CONSTRAINT "FK_0fcad94dc3f7b8b86c2f4547820"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP CONSTRAINT "FK_1656846e99e03d03402bf71a343"`);
        await queryRunner.query(`ALTER TABLE "company_subscription" DROP CONSTRAINT "FK_f8b117158ab95f921469ff24a3e"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "UQ_0f5e404ec6b146ea06d1c429f6c"`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" DROP CONSTRAINT "UQ_a6d0f15eff6e28524b4fa898602"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7e38cdc6dc7765b30447cd06d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f64c424d932c9718ec6da80e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e08a5064905cd0c9513e39ce8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b7a3621aa5ecdb3105c74e9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b75639be4adf19e9920f7c374"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f45e8a6455829dad6638dd0b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec74546492517ad86802c5c913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f8a7f45f7acb51e680aa85cdd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5978c41e6e06f58a7db5259802"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17c31b236f5a8fcf717a4b6e5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd9e3b69626be360af7cf0d923"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21824dd676afb8c2810ad30290"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1beaa4671be609e6a63b2b17ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fcad94dc3f7b8b86c2f454782"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8b117158ab95f921469ff24a3"`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "expires_at" TYPE TIMESTAMP WITH TIME ZONE USING "expires_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ALTER COLUMN "activated_at" TYPE TIMESTAMP WITH TIME ZONE USING "activated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "paid_at" TYPE TIMESTAMP WITH TIME ZONE USING "paid_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "payment_order" ALTER COLUMN "payment_method" SET DEFAULT 'vnpay'`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "proceeds_reset_at" TYPE TIMESTAMP WITH TIME ZONE USING "proceeds_reset_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "last_job_published_at" TYPE TIMESTAMP WITH TIME ZONE USING "last_job_published_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "end_date" TYPE TIMESTAMP WITH TIME ZONE USING "end_date"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ALTER COLUMN "start_date" TYPE TIMESTAMP WITH TIME ZONE USING "start_date"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "bumped_at" TYPE TIMESTAMP WITH TIME ZONE USING "bumped_at"::timestamp with time zone`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD "headhunting_views_reset_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD "headhunting_views_used" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "candidate" ADD "level_id" integer`);
        await queryRunner.query(`ALTER TABLE "job_application" ADD "ai_scored" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "job_application" ADD "screening_passed" boolean`);
        await queryRunner.query(`ALTER TABLE "application_status_history" ADD "credit_charged" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "UQ_saved_job_candidate_job" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" ADD CONSTRAINT "UQ_job_profile_view" UNIQUE ("job_id", "candidate_id")`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "UQ_contact_unlock_log" UNIQUE ("company_id", "candidate_id")`);
        await queryRunner.query(`ALTER TABLE "screening_answer" ADD CONSTRAINT "UQ_screening_answer" UNIQUE ("application_id", "question_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_saved_job_job_id" ON "saved_job" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_saved_job_candidate_id" ON "saved_job" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_credit_purchase_log_company_id" ON "credit_purchase_log" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_credit_transaction_wallet_id" ON "credit_transaction" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_profile_view_job_id" ON "job_profile_view" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_order_gateway_order_id" ON "payment_order" ("gateway_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_order_company_id" ON "payment_order" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_contact_unlock_log_company_id" ON "contact_unlock_log" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_screening_question_job_id" ON "screening_question" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_screening_answer_application_id" ON "screening_answer" ("application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_company_subscription_company_id" ON "company_subscription" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_67170af9a05e67ebf48434db68" ON "candidate" ("level_id") `);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_saved_job_job" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_saved_job_candidate" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_credit_purchase_log_product" FOREIGN KEY ("product_id") REFERENCES "credit_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_credit_purchase_log_job" FOREIGN KEY ("target_job_id") REFERENCES "job"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_purchase_log" ADD CONSTRAINT "FK_credit_purchase_log_company" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transaction" ADD CONSTRAINT "FK_credit_transaction_wallet" FOREIGN KEY ("wallet_id") REFERENCES "credit_wallet"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_wallet" ADD CONSTRAINT "FK_credit_wallet_company" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" ADD CONSTRAINT "FK_job_profile_view_job" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_profile_view" ADD CONSTRAINT "FK_job_profile_view_candidate" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_order" ADD CONSTRAINT "FK_payment_order_package" FOREIGN KEY ("package_id") REFERENCES "subscription_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_order" ADD CONSTRAINT "FK_payment_order_company" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "FK_contact_unlock_log_company" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_unlock_log" ADD CONSTRAINT "FK_contact_unlock_log_candidate" FOREIGN KEY ("candidate_id") REFERENCES "candidate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_question" ADD CONSTRAINT "FK_screening_question_job" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_answer" ADD CONSTRAINT "FK_screening_answer_question" FOREIGN KEY ("question_id") REFERENCES "screening_question"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening_answer" ADD CONSTRAINT "FK_screening_answer_application" FOREIGN KEY ("application_id") REFERENCES "job_application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD CONSTRAINT "FK_company_subscription_package" FOREIGN KEY ("package_id") REFERENCES "subscription_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_subscription" ADD CONSTRAINT "FK_company_subscription_company" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate" ADD CONSTRAINT "FK_67170af9a05e67ebf48434db686" FOREIGN KEY ("level_id") REFERENCES "job_level_metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
